### PR TITLE
add counter to links for easier navigation

### PR DESCRIPTION
**Pull request by guzzisti**
Links on the page are rendered with a counter in front of them for easier navigation.

The links view is still in place to allow checking of URIs before navigation. But on pages with many links it's hard to find the desired line with links view only.

I'm currently unsure whats the best way to show the counter. Feedback welcome.

### CODE REVIEW

**Comment by blmayer** [comment]
Hi,

I think we should let the users choose how to show the counter, this settings could be part of the link style, e.g.:

Config file:
```
style-link-bullet=33($linkcounter) =>
```

So the code that applies the style is: `line="$sty_linkb$sty_linkt $line"`, but `$sty_linkb` would have the counter inside, and would expand to: `\\033[35m[$linkcounter] =>`.

And import this into the style. For the default I'd like to have the link counter inside the margin:

```
        Some text.
   [1]  => link to some page
```

But this would require a bigger change. For now I think just adding the counter before the link is good:
```
        Some text.
        [1] link to some page
```

The link text would still be in italics, so users will know it is a link.

**Comment by guzzisti** [comment]
very reasonable. I gonna change it.

**Comment by guzzisti** [comment]
Sorry for the late response. I'm currently too stupid to make it work like i'd like to...may take some time till i'l get things sorted out.

**Comment by blmayer** [comment]
Thanks for getting back. Never mind the time, I only plan to work on astro in a few weeks.

**Comment by guzzisti** [comment]
I currently don't get around to finally finish this, will come back later with a new PR.

**Comment by blmayer** [comment]
No problem.

**Pull request closed without merging**
