### PR TITLE
trace and first step in performance

### PR DESCRIPTION
**Pull request by rnwgnr**
This PR adds a simple function to trace the time spend in code sections. It can be enabled by setting `trace=1` when launching astro and will create a trace file in astro's cache dir.

Additionally the rendering of links has been modified to remove character replacement via `sed` which improves performance of link rendering a lot.

### CODE REVIEW

**Comment by blmayer** [comment]
But that could be done in another time If don't want to change this PR.

**Comment by rnwgnr** [comment]
> Does adding this code decreases performance even with trace=""

The difference may be measurable but for sure not something that has a remarkable impact of the overall performance. We essentially have an additional function call and a check, pretty much the same we have for the "debug" calls. This would add fractions of milliseconds.

**Comment by blmayer** [comment]
All right. Thanks for working on this.

**Comment by rnwgnr** [comment]
The change introduces issues on some capsules when interpreting link lines. I will look into it and try to fix this.

**Pull request merged**
